theme: minima

author:
  name: Sten Remmelg
  email: sten.remmelg@gmail.com

minima:
  skin: dark

  social_links:
   - { platform: instagram,      user_url: "https://www.instagram.com/steniinsta/" }
   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/stenremmelg/" }