theme: minima

author:
  name: Sten Remmelg
  email: sten.remmelg@gmail.com

description: >
  Writings about analysis experiments in cheer stunting and tumbling, as well as tech related related topics around the same area.

header_pages:
  - contact.md
  - more.md

minima:
  skin: dark

  social_links:
   - { platform: instagram,      user_url: "https://www.instagram.com/steniinsta/" }
   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/stenremmelg/" }
   - { platform: github,         user_url: "https://github.com/sremm"}